### ISSUE TITLE
Unable to run on LinuxMint

### ISSUE THREAD

**Issue by bhaskar-c** [FormidableLabs/react-music#44]
Hi
Thanks for this program. Using this for a while on Windows and this works great.
However running `npm start` gives the following unhelpful error message on Linux mint:
```
~/Desktop/Music/react-music-master $ npm start

> react-music@1.0.2 start /home/gublu/Desktop/Music/react-music-master
> webpack-dev-server --hot --inline --port 3000 --config webpack.config.dev.js --content-base public/

module.js:471
    throw err;
    ^

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gublu/Desktop/Music/react-music-master/node_modules/readable-stream/lib/_stream_readable.js:37:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-music@1.0.2 start: `webpack-dev-server --hot --inline --port 3000 --config webpack.config.dev.js --content-base public/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-music@1.0.2 start script 'webpack-dev-server --hot --inline --port 3000 --config webpack.config.dev.js --content-base public/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-music package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --port 3000 --config webpack.config.dev.js --content-base public/

```
I have already tried reinstalling nodejs and npm and my versions are latest.
node v6.10.3
npm  v3.10.10

But this does not seem to work.

**Comment by bhaskar-c** [comment]
Please close this issue.

I did not run npm i and hence the error.
